# Generated by Django 4.2.7 on 2023-12-01 07:31

from django.db import migrations, models
import virtualfriend.models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfriend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualfriend',
            name='friend_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=virtualfriend.models.user_directory_path),
        ),
    ]
