# Generated by Django 4.2.7 on 2023-12-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfriend', '0003_virtualfriend_friend_mbti'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualfriend',
            name='friend_mbti_variant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
