# Generated by Django 4.2.7 on 2023-12-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfriend', '0005_alter_virtualfriend_friend_initial_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualfriend',
            old_name='friend_initial_prompt',
            new_name='friend_custom_prompt',
        ),
    ]
