# Generated by Django 4.2.7 on 2023-12-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfriend', '0006_rename_friend_initial_prompt_virtualfriend_friend_custom_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualfriend',
            name='friend_avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
