# Generated by Django 4.2.7 on 2023-12-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='create_timestamp',
        ),
        migrations.AddField(
            model_name='profile',
            name='mbti_variant',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
